<a href="https://colab.research.google.com/github/Preethi-140306/MLOPS_Training/blob/main/project_implemented_OneHotEncoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving cleaned_women_safety.csv to cleaned_women_safety.csv

In [ ]:
import pandas as pd
df = pd.read_csv('cleaned_women_safety.csv')
df.head()

                       text  label
0           feel safe right      2
1  pls help someone chasing      3
2                call maybe      2
3                     place      2
4                call maybe      1

In [ ]:
dummies=pd.get_dummies(df.label)
dummies

        0      1      2      3
0   False  False   True  False
1   False  False  False   True
2   False  False   True  False
3   False  False   True  False
4   False   True  False  False
..    ...    ...    ...    ...
61  False  False   True  False
62  False   True  False  False
63  False   True  False  False
64  False   True  False  False
65   True  False  False  False

[66 rows x 4 columns]

In [ ]:
merged = pd.concat([df,dummies],axis='columns')
merged

                            text  label      0      1      2      3
0                feel safe right      2  False  False   True  False
1       pls help someone chasing      3  False  False  False   True
2                     call maybe      2  False  False   True  False
3                          place      2  False  False   True  False
4                     call maybe      1  False   True  False  False
..                           ...    ...    ...    ...    ...    ...
61                         check      2  False  False   True  False
62  harassment happened bus stop      1  False   True  False  False
63             guysss help meeee      1  False   True  False  False
64        help someone following      1  False   True  False  False
65               feel safe right      0   True  False  False  False

[66 rows x 6 columns]

In [ ]:
final = merged.drop(['label'],axis='columns')
final

                            text      0      1      2      3
0                feel safe right  False  False   True  False
1       pls help someone chasing  False  False  False   True
2                     call maybe  False  False   True  False
3                          place  False  False   True  False
4                     call maybe  False   True  False  False
..                           ...    ...    ...    ...    ...
61                         check  False  False   True  False
62  harassment happened bus stop  False   True  False  False
63             guysss help meeee  False   True  False  False
64        help someone following  False   True  False  False
65               feel safe right   True  False  False  False

[66 rows x 5 columns]

In [ ]:
final=final.drop([2], axis='columns')
final

                            text      0      1      3
0                feel safe right  False  False  False
1       pls help someone chasing  False  False   True
2                     call maybe  False  False  False
3                          place  False  False  False
4                     call maybe  False   True  False
..                           ...    ...    ...    ...
61                         check  False  False  False
62  harassment happened bus stop  False   True  False
63             guysss help meeee  False   True  False
64        help someone following  False   True  False
65               feel safe right   True  False  False

[66 rows x 4 columns]

In [ ]:
X=final.drop(['text'],axis='columns')
X

        0      1      3
0   False  False  False
1   False  False   True
2   False  False  False
3   False  False  False
4   False   True  False
..    ...    ...    ...
61  False  False  False
62  False   True  False
63  False   True  False
64  False   True  False
65   True  False  False

[66 rows x 3 columns]

In [ ]:
y=df.label

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X, y)
print(model.predict(X))
print(model.score(X,y))

[2. 3. 2. 2. 1. 1. 0. 1. 3. 0. 3. 3. 1. 2. 1. 1. 0. 0. 1. 0. 2. 1. 1. 0.
 2. 0. 0. 3. 1. 3. 1. 0. 1. 3. 2. 1. 0. 3. 3. 2. 2. 1. 3. 3. 2. 2. 1. 0.
 2. 0. 0. 3. 0. 0. 2. 0. 0. 1. 3. 0. 3. 2. 1. 1. 1. 0.]
1.0

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
dfle = df.copy()

dfle.label = le.fit_transform(dfle.label)
dfle

                            text  label
0                feel safe right      2
1       pls help someone chasing      3
2                     call maybe      2
3                          place      2
4                     call maybe      1
..                           ...    ...
61                         check      2
62  harassment happened bus stop      1
63             guysss help meeee      1
64        help someone following      1
65               feel safe right      0

[66 rows x 2 columns]

In [ ]:
X = dfle[['label']].values
X

array([[2],
       [3],
       [2],
       [2],
       [1],
       [1],
       [0],
       [1],
       [3],
       [0],
       [3],
       [3],
       [1],
       [2],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [2],
       [1],
       [1],
       [0],
       [2],
       [0],
       [0],
       [3],
       [1],
       [3],
       [1],
       [0],
       [1],
       [3],
       [2],
       [1],
       [0],
       [3],
       [3],
       [2],
       [2],
       [1],
       [3],
       [3],
       [2],
       [2],
       [1],
       [0],
       [2],
       [0],
       [0],
       [3],
       [0],
       [0],
       [2],
       [0],
       [0],
       [1],
       [3],
       [0],
       [3],
       [2],
       [1],
       [1],
       [1],
       [0]])

In [ ]:
y = dfle.label.values
y

array([2, 3, 2, 2, 1, 1, 0, 1, 3, 0, 3, 3, 1, 2, 1, 1, 0, 0, 1, 0, 2, 1,
       1, 0, 2, 0, 0, 3, 1, 3, 1, 0, 1, 3, 2, 1, 0, 3, 3, 2, 2, 1, 3, 3,
       2, 2, 1, 0, 2, 0, 0, 3, 0, 0, 2, 0, 0, 1, 3, 0, 3, 2, 1, 1, 1, 0])

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(
    [('label', OneHotEncoder(sparse_output=False), [0])],
    remainder='passthrough'
)
X = ct.fit_transform(X)
X

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [ ]:
X = X[:, 1:]
X

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.]])

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X, y)
model.predict(X)

array([ 2.00000000e+00,  3.00000000e+00,  2.00000000e+00,  2.00000000e+00,
        1.00000000e+00,  1.00000000e+00, -2.22044605e-16,  1.00000000e+00,
        3.00000000e+00, -2.22044605e-16,  3.00000000e+00,  3.00000000e+00,
        1.00000000e+00,  2.00000000e+00,  1.00000000e+00,  1.00000000e+00,
       -2.22044605e-16, -2.22044605e-16,  1.00000000e+00, -2.22044605e-16,
        2.00000000e+00,  1.00000000e+00,  1.00000000e+00, -2.22044605e-16,
        2.00000000e+00, -2.22044605e-16, -2.22044605e-16,  3.00000000e+00,
        1.00000000e+00,  3.00000000e+00,  1.00000000e+00, -2.22044605e-16,
        1.00000000e+00,  3.00000000e+00,  2.00000000e+00,  1.00000000e+00,
       -2.22044605e-16,  3.00000000e+00,  3.00000000e+00,  2.00000000e+00,
        2.00000000e+00,  1.00000000e+00,  3.00000000e+00,  3.00000000e+00,
        2.00000000e+00,  2.00000000e+00,  1.00000000e+00, -2.22044605e-16,
        2.00000000e+00, -2.22044605e-16, -2.22044605e-16,  3.00000000e+00,
       -2.22044605e-16, -2.22044605e-16,  2.00000000e+00, -2.22044605e-16,
       -2.22044605e-16,  1.00000000e+00,  3.00000000e+00, -2.22044605e-16,
        3.00000000e+00,  2.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00, -2.22044605e-16])

In [ ]:
import joblib
joblib.dump(ct, 'encoder.joblib')
joblib.dump(model, 'model.joblib')
model = joblib.load('model.joblib')
ct = joblib.load('encoder.joblib')
print("The OneHotEncoder is saved as joblib file successfully")

The OneHotEncoder is saved as joblib file successfully

In [ ]:
model.coef_

array([1., 2., 3.])

In [ ]:
model.intercept_

np.float64(-2.220446049250313e-16)